---
version: "2.0"

services:
  web:
    image: rodrirr/mining-on-akash-web:0.2.0
    expose:
      - port: 80
        as: 80
        accept:
          - mining-on-akash.xyz
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 5Gi
  placement:
    westcoast:
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    westcoast:
      profile: web
      count: 1
